import { StyleSheet } from 'react-native';
import colors from '@/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
  },
  title: {
    fontSize: 26,
    fontWeight: '800' as const,
    color: colors.text,
    letterSpacing: -0.5,
  },
  headerBadge: {
    marginLeft: 8,
    padding: 4,
  },
  tabBar: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    gap: 10,
    marginBottom: 14,
  },
  tabPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.borderLight,
  },
  tabPillActive: {
    backgroundColor: colors.primary,
    borderColor: colors.black,
  },
  tabPillText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.text,
  },
  tabPillTextActive: {
    color: colors.white,
  },
  tabBadgeCount: {
    backgroundColor: colors.borderLight,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    paddingHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabBadgeCountActive: {
    backgroundColor: 'rgba(255,255,255,0.3)',
  },
  tabBadgeCountText: {
    fontSize: 11,
    fontWeight: '800' as const,
    color: colors.textSecondary,
  },
  tabBadgeCountTextActive: {
    color: colors.white,
  },
  scroll: {
    flex: 1,
    paddingHorizontal: 20,
  },
  section: {
    marginBottom: 28,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  sectionBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.black,
  },
  sectionBadgeReady: {
    backgroundColor: colors.mint,
  },
  sectionBadgeAlmost: {
    backgroundColor: colors.comic.yellow,
  },
  sectionBadgeTrip: {
    backgroundColor: colors.comic.blue,
  },
  sectionBadgeText: {
    fontSize: 11,
    fontWeight: '800' as const,
    color: colors.black,
    letterSpacing: 0.5,
  },
  sectionCount: {
    marginLeft: 10,
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.textSecondary,
  },
  sectionLine: {
    flex: 1,
    height: 2,
    backgroundColor: colors.borderLight,
    marginLeft: 12,
  },
  recipeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
  },
  recipeCardReady: {
    backgroundColor: colors.mintLight,
  },
  cardTilt: {
    transform: [{ rotate: '-0.5deg' }],
  },
  cardContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  cardIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
  },
  cardEmoji: {
    fontSize: 20,
  },
  cardInfo: {
    flex: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 2,
  },
  cardReady: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.success,
  },
  cardMissing: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  cardMatchBar: {
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.borderLight,
    overflow: 'hidden' as const,
  },
  cardMatchBarFill: {
    height: '100%' as const,
    borderRadius: 2,
    backgroundColor: colors.comic.yellow,
  },
  cardMatchBarFillWeak: {
    backgroundColor: colors.comic.blue,
  },
  cookBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  cookBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.white,
  },
  addListBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.secondaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addListBtnAlt: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.cardAlt,
    borderWidth: 2,
    borderColor: colors.borderLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  recipeCardExpanded: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
  },
  missingItemsList: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  missingItemsLabel: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: colors.error,
    marginBottom: 6,
    letterSpacing: 0.3,
  },
  missingItemRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingVertical: 3,
  },
  missingItemDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.error,
    marginRight: 8,
  },
  missingItemName: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.text,
    textTransform: 'capitalize' as const,
  },
  missingItemMore: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: colors.textSecondary,
    marginTop: 4,
    marginLeft: 14,
  },
  addToGroceryCardBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 8,
    backgroundColor: colors.secondary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 12,
    paddingVertical: 10,
    marginTop: 12,
  },
  addToGroceryCardBtnText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.white,
  },
  addToGroceryCardBtnAlt: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 8,
    backgroundColor: colors.secondaryLight,
    borderWidth: 2,
    borderColor: colors.secondary,
    borderRadius: 12,
    paddingVertical: 10,
    marginTop: 12,
  },
  addToGroceryCardBtnAltText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  flowHintCard: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    gap: 8,
    backgroundColor: colors.secondaryLight,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.secondary + '40',
    padding: 14,
    marginBottom: 16,
  },
  flowHintEmoji: {
    fontSize: 16,
    marginTop: 1,
  },
  flowHintText: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.text,
    lineHeight: 19,
  },
  flowHintBold: {
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  emptyContainer: {
    flex: 1,
  },
  emptyContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 120,
  },
  progressCard: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
  },
  progressTitle: {
    fontSize: 16,
    fontWeight: '800' as const,
    color: colors.text,
  },
  progressSubtitle: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  progressRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressStep: {
    flex: 1,
    backgroundColor: colors.cardAlt,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  progressStepActive: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  progressStepComplete: {
    backgroundColor: colors.mintLight,
    borderColor: colors.mint,
  },
  progressStepInactive: {
    opacity: 0.6,
  },
  progressStepNumberWrap: {
    width: 26,
    height: 26,
    borderRadius: 10,
    backgroundColor: colors.text,
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressStepNumberWrapComplete: {
    backgroundColor: colors.success,
  },
  progressStepNumber: {
    fontSize: 13,
    fontWeight: '800' as const,
    color: colors.white,
  },
  progressStepText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.text,
  },
  progressStepCount: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: colors.success,
    marginTop: 1,
  },
  progressStepLine: {
    width: 16,
    height: 2,
    backgroundColor: colors.borderLight,
    marginHorizontal: 10,
  },
  tipsCard: {
    marginTop: 14,
    backgroundColor: colors.secondaryLight,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: colors.borderLight,
    padding: 16,
  },
  tipsTitle: {
    fontSize: 13,
    fontWeight: '800' as const,
    color: colors.secondary,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  tipsText: {
    marginTop: 6,
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.text,
    lineHeight: 20,
  },
  emptyCard: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  emptyDecor: {
    position: 'absolute',
    top: -20,
    right: -20,
    width: 100,
    height: 100,
  },
  decorCircle: {
    position: 'absolute',
    borderRadius: 50,
    borderWidth: 2,
    borderColor: colors.borderLight,
  },
  decorCircle1: {
    width: 60,
    height: 60,
    top: 10,
    right: 10,
  },
  decorCircle2: {
    width: 40,
    height: 40,
    top: 40,
    right: 50,
  },
  decorCircle3: {
    width: 20,
    height: 20,
    top: 60,
    right: 20,
  },
  emptyTotie: {
    width: 110,
    height: 110,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptySubtext: {
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  emptyActions: {
    flexDirection: 'row',
    gap: 10,
  },
  emptyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  emptyBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.white,
  },
  emptyAISection: {
    marginTop: 20,
    alignItems: 'center',
    width: '100%',
  },
  emptyAIDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '80%',
    marginBottom: 16,
  },
  emptyAIDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.borderLight,
  },
  emptyAIDividerText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.textSecondary,
    paddingHorizontal: 12,
  },
  emptyAIBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.secondary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  emptyAIBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.white,
  },
  emptyAIHint: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 8,
    textAlign: 'center',
  },
  bottomPadding: {
    height: 20,
  },
  noMatchesCard: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    marginTop: 20,
  },
  noMatchesTotie: {
    width: 100,
    height: 100,
    marginBottom: 16,
  },
  noMatchesTitle: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
  },
  noMatchesText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  suggestCard: {
    width: '100%',
    backgroundColor: colors.cardAlt,
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
  },
  suggestCardTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 4,
  },
  suggestCardSubtitle: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginBottom: 12,
  },
  suggestRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  suggestDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primary,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    marginRight: 10,
  },
  suggestDotText: {
    fontSize: 12,
    fontWeight: '800' as const,
    color: colors.white,
  },
  suggestInfo: {
    flex: 1,
  },
  suggestName: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
    textTransform: 'capitalize' as const,
  },
  suggestMeta: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 2,
  },
  suggestAddBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.secondaryLight,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    marginLeft: 8,
  },
  suggestBtnRow: {
    flexDirection: 'row' as const,
    gap: 8,
    marginTop: 14,
  },
  suggestGroceryBtn: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
    backgroundColor: colors.secondaryLight,
    borderWidth: 1.5,
    borderColor: colors.secondary,
    borderRadius: 12,
    paddingVertical: 12,
  },
  suggestGroceryBtnText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  suggestUpdateKitchenBtn: {
    flex: 1,
    backgroundColor: colors.secondary,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  suggestUpdateKitchenText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.white,
  },
  boostCard: {
    backgroundColor: colors.secondaryLight,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: colors.borderLight,
    padding: 16,
    marginBottom: 16,
  },
  boostTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
  },
  boostSubtitle: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 4,
    marginBottom: 12,
  },
  boostChips: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: 8,
  },
  boostChip: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.borderLight,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  boostChipText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.text,
    textTransform: 'capitalize' as const,
  },
  boostChipCount: {
    fontSize: 11,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  boostAddAllBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
    marginTop: 14,
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.secondary,
    borderRadius: 12,
    paddingVertical: 10,
  },
  boostAddAllBtnText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  noMatchesActions: {
    flexDirection: 'row',
    gap: 10,
  },
  noMatchesBtn: {
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
  },
  noMatchesBtnAlt: {
    backgroundColor: colors.white,
  },
  noMatchesBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.white,
  },
  noMatchesBtnTextAlt: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
  },
  aiSuggestBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: colors.secondary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 24,
    width: '100%',
    marginBottom: 16,
  },
  aiSuggestBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
  aiSuggestHint: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center' as const,
    marginTop: -8,
    marginBottom: 8,
    width: '100%',
  },
  aiSuggestHintAlt: {
    fontSize: 11,
    color: colors.textSecondary,
    textAlign: 'center' as const,
    marginTop: 4,
    marginBottom: 12,
  },
  noMatchesDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    width: '100%',
  },
  noMatchesDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: colors.borderLight,
  },
  noMatchesDividerText: {
    marginHorizontal: 12,
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  recipeBreakdownCard: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.borderLight,
    padding: 16,
    marginBottom: 20,
  },
  recipeBreakdownTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 4,
  },
  recipeBreakdownSubtitle: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginBottom: 14,
  },
  recipeBreakdownRow: {
    backgroundColor: colors.cardAlt,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  recipeBreakdownHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    marginBottom: 8,
  },
  recipeBreakdownName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    marginRight: 8,
  },
  recipeBreakdownPercent: {
    backgroundColor: colors.comic.blue + '30',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  recipeBreakdownPercentText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: colors.text,
  },
  recipeBreakdownBar: {
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.borderLight,
    overflow: 'hidden' as const,
    marginBottom: 8,
  },
  recipeBreakdownBarFill: {
    height: '100%' as const,
    borderRadius: 2,
    backgroundColor: colors.comic.blue,
  },
  recipeBreakdownHave: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.success,
    marginBottom: 4,
  },
  recipeBreakdownNeed: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.error,
    marginBottom: 8,
  },
  recipeBreakdownAddBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    alignSelf: 'flex-start' as const,
    gap: 6,
    backgroundColor: colors.secondaryLight,
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  recipeBreakdownAddText: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: colors.secondary,
  },
  aiModalTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  aiRecipeHeader: {
    padding: 20,
    backgroundColor: colors.white,
    borderBottomWidth: 2,
    borderBottomColor: colors.borderLight,
  },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: colors.secondary,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 12,
  },
  aiBadgeText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: colors.white,
  },
  tipsSection: {
    marginHorizontal: 20,
    marginTop: 8,
    backgroundColor: colors.secondaryLight,
    borderRadius: 16,
    padding: 16,
  },
  tipsSectionTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 8,
  },
  tipsSectionText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  regenerateBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.secondaryLight,
    borderWidth: 2,
    borderColor: colors.secondary,
    borderRadius: 14,
    paddingVertical: 14,
  },
  regenerateBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  modalSafeArea: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: colors.borderLight,
    backgroundColor: colors.white,
  },
  modalCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.cardAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700' as const,
    color: colors.text,
    textAlign: 'center',
    marginHorizontal: 12,
  },
  modalSourceBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  modalDeleteBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#FFF0F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalScroll: {
    flex: 1,
  },
  recipeImage: {
    width: '100%',
    height: 200,
    backgroundColor: colors.cardAlt,
  },
  recipeHeader: {
    padding: 20,
    backgroundColor: colors.white,
    borderBottomWidth: 2,
    borderBottomColor: colors.borderLight,
  },
  recipeTitle: {
    fontSize: 24,
    fontWeight: '800' as const,
    color: colors.text,
    letterSpacing: -0.5,
    marginBottom: 12,
  },
  recipeMeta: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 16,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  metaText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  matchBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
  },
  matchBadgeReady: {
    backgroundColor: colors.mintLight,
  },
  matchBadgeMissing: {
    backgroundColor: colors.comic.yellow + '30',
  },
  matchBadgeText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 14,
  },
  ingredientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  ingredientRowMissing: {
    backgroundColor: colors.primaryLight + '40',
    marginHorizontal: -20,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginBottom: 4,
    borderBottomWidth: 0,
  },
  ingredientDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.success,
    marginRight: 12,
  },
  ingredientDotMissing: {
    backgroundColor: colors.error,
  },
  ingredientText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.text,
  },
  ingredientTextMissing: {
    color: colors.text,
  },
  missingLabel: {
    fontSize: 11,
    fontWeight: '700' as const,
    color: colors.error,
    backgroundColor: colors.white,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
  },
  instructionRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  instructionNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  instructionNumberText: {
    fontSize: 14,
    fontWeight: '800' as const,
    color: colors.white,
  },
  instructionText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.text,
    lineHeight: 22,
  },
  modalBottomPadding: {
    height: 120,
  },
  modalActions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 32,
    backgroundColor: colors.white,
    borderTopWidth: 2,
    borderTopColor: colors.borderLight,
  },
  addGroceryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.secondaryLight,
    borderWidth: 2,
    borderColor: colors.secondary,
    borderRadius: 14,
    paddingVertical: 14,
  },
  addGroceryBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  startCookingBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    paddingVertical: 14,
  },
  startCookingBtnAlt: {
    flex: 0.8,
  },
  startCookingBtnText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.white,
  },
  cookingContainer: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  cookingSafeArea: {
    flex: 1,
  },
  cookingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  cookingBackBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cookingTitleWrap: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 12,
  },
  cookingTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: colors.white,
  },
  cookingProgress: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: 'rgba(255,255,255,0.7)',
    marginTop: 2,
  },
  cookingProgressBar: {
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginHorizontal: 16,
    borderRadius: 2,
    overflow: 'hidden',
  },
  cookingProgressFill: {
    height: '100%',
    backgroundColor: colors.white,
    borderRadius: 2,
  },
  cookingContent: {
    flex: 1,
    marginTop: 24,
  },
  cookingContentInner: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  stepCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    minHeight: 200,
  },
  stepNumberBadge: {
    alignSelf: 'flex-start',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  stepNumberText: {
    fontSize: 18,
    fontWeight: '800' as const,
    color: colors.white,
  },
  stepInstruction: {
    fontSize: 20,
    fontWeight: '600' as const,
    color: colors.text,
    lineHeight: 30,
  },
  cookingNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 12,
  },
  cookingNavBtn: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  cookingNavBtnDisabled: {
    opacity: 0.4,
  },
  cookingNavBtnText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.white,
  },
  cookingNavBtnTextDisabled: {
    opacity: 0.5,
  },
  nextBtn: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.white,
    borderRadius: 14,
    paddingVertical: 14,
  },
  nextBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.primary,
  },
  finishBtn: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.success,
    borderRadius: 14,
    paddingVertical: 14,
  },
  finishBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
  bonusSection: {
    marginTop: 8,
    padding: 16,
    backgroundColor: colors.cardAlt,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderStyle: 'dashed',
  },
  bonusLabel: {
    fontSize: 12,
    fontWeight: '800' as const,
    color: colors.textSecondary,
    letterSpacing: 1,
    marginBottom: 12,
    textAlign: 'center',
  },
  nextActionsCard: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 20,
    padding: 18,
    marginTop: 8,
  },
  nextActionsTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 14,
  },
  nextActionsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  nextActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.secondary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    paddingVertical: 14,
  },
  nextActionBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.white,
  },
  nextActionBtnAlt: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.secondaryLight,
    borderWidth: 2,
    borderColor: colors.secondary,
    borderRadius: 14,
    paddingVertical: 14,
  },
  nextActionBtnAltText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  nextActionRefresh: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 6,
  },
  nextActionRefreshText: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  addRecipeBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
    backgroundColor: colors.primaryLight,
    borderWidth: 2,
    borderColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 12,
    marginBottom: 12,
  },
  addRecipeBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.primary,
  },
  addRecipeOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    padding: 24,
  },
  addRecipeModal: {
    width: '100%' as const,
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    borderWidth: 2,
    borderColor: colors.black,
  },
  addRecipeModalHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    marginBottom: 20,
  },
  addRecipeModalTitle: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: colors.text,
  },
  addRecipeTypeSelector: {
    flexDirection: 'row' as const,
    backgroundColor: colors.cardAlt,
    borderRadius: 12,
    padding: 4,
    marginBottom: 20,
  },
  addRecipeTypeTab: {
    flex: 1,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  addRecipeTypeTabActive: {
    backgroundColor: colors.secondary,
  },
  addRecipeTypeTabText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
  },
  addRecipeTypeTabTextActive: {
    color: colors.white,
  },
  addRecipeInputGroup: {
    marginBottom: 20,
  },
  addRecipeInputLabel: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.text,
    marginBottom: 8,
  },
  addRecipeTextInput: {
    backgroundColor: colors.cardAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.borderLight,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.text,
  },
  addRecipeTextInputMultiline: {
    minHeight: 80,
    textAlignVertical: 'top' as const,
  },
  addRecipeSubmitBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 8,
    backgroundColor: '#F59E0B',
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    paddingVertical: 16,
  },
  addRecipeSubmitBtnDisabled: {
    opacity: 0.5,
  },
  addRecipeSubmitBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
  completedEmptyCard: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    marginTop: 20,
  },
  completedEmptyIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  completedEmptyTitle: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
  },
  completedEmptySubtext: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 24,
  },
  completedEmptyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  completedEmptyBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.white,
  },
  completedSummary: {
    backgroundColor: colors.mintLight,
    borderWidth: 2,
    borderColor: colors.mint,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    marginTop: 4,
  },
  completedSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  completedStat: {
    flex: 1,
    alignItems: 'center',
  },
  completedStatNumber: {
    fontSize: 24,
    fontWeight: '800' as const,
    color: colors.text,
  },
  completedStatLabel: {
    fontSize: 12,
    fontWeight: '600' as const,
    color: colors.textSecondary,
    marginTop: 2,
  },
  completedStatDivider: {
    width: 1,
    height: 32,
    backgroundColor: colors.mint,
    marginHorizontal: 16,
  },
  completedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: 16,
    padding: 12,
    marginBottom: 10,
  },
  completedCardImage: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: colors.cardAlt,
  },
  completedCardImagePlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  completedCardInfo: {
    flex: 1,
    marginLeft: 12,
  },
  completedCardTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 4,
  },
  completedCardMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  completedCardTime: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  completedAIBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: colors.secondaryLight,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  completedAIBadgeText: {
    fontSize: 10,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  completedCardSavings: {
    alignItems: 'center',
    marginLeft: 8,
    backgroundColor: colors.mintLight,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  completedCardSavingsText: {
    fontSize: 15,
    fontWeight: '800' as const,
    color: colors.success,
  },
  completedCardSavingsLabel: {
    fontSize: 10,
    fontWeight: '600' as const,
    color: colors.success,
  },
  cookAnotherBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    paddingVertical: 14,
    marginTop: 8,
  },
  cookAnotherBtnText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.white,
  },
  addedToGroceryBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 8,
    backgroundColor: colors.mintLight,
    borderWidth: 2,
    borderColor: colors.mint,
    borderRadius: 12,
    paddingVertical: 10,
    marginTop: 12,
  },
  addedToGroceryBadgeText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.success,
  },
  nextStepBanner: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    backgroundColor: colors.secondaryLight,
    borderWidth: 1.5,
    borderColor: colors.secondary + '50',
    borderRadius: 12,
    padding: 12,
    marginTop: 8,
  },
  nextStepLeft: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    flex: 1,
    gap: 10,
  },
  nextStepIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.secondary,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  nextStepTextWrap: {
    flex: 1,
  },
  nextStepTitle: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  nextStepSubtext: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 2,
  },
});
