import { StyleSheet } from 'react-native';
import colors from '@/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: '800' as const,
    color: colors.text,
    letterSpacing: -0.5,
  },
  searchBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabBar: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginBottom: 20,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    padding: 3,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderRadius: 10,
    gap: 6,
  },
  tabActive: {
    backgroundColor: colors.text,
  },
  tabEmoji: {
    fontSize: 18,
  },
  tabText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.textSecondary,
  },
  tabTextActive: {
    color: colors.white,
  },
  scroll: {
    flex: 1,
    paddingHorizontal: 20,
  },
  categorySection: {
    marginBottom: 24,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  categoryEmoji: {
    fontSize: 20,
    marginRight: 8,
  },
  categoryTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.text,
    flex: 1,
  },
  categoryCount: {
    backgroundColor: colors.textSecondary,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  categoryCountText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: colors.white,
  },
  itemsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  itemSquare: {
    width: '30%' as unknown as number,
    aspectRatio: 1,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
    position: 'relative',
  },
  itemSquareDelete: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  itemSquareEmoji: {
    fontSize: 36,
    marginBottom: 4,
  },
  itemSquareName: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: colors.text,
    textAlign: 'center',
    lineHeight: 15,
  },
  itemSquareQty: {
    fontSize: 10,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 2,
    textAlign: 'center',
  },
  emptyContainer: {
    flex: 1,
  },
  emptyContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 120,
  },
  quickAddCard: {
    backgroundColor: colors.cardAlt,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
  },
  quickAddHeader: {
    marginBottom: 12,
  },
  quickAddTitle: {
    fontSize: 16,
    fontWeight: '800' as const,
    color: colors.text,
    letterSpacing: -0.2,
  },
  quickAddSubtitle: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  quickAddRow: {
    gap: 10,
    paddingRight: 6,
  },
  quickAddPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
  },
  quickAddPillText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
  },
  emptyCard: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
  },
  emptyTotie: {
    width: 100,
    height: 100,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  addOptions: {
    flexDirection: 'row',
    gap: 12,
  },
  addOption: {
    alignItems: 'center',
    backgroundColor: colors.cardAlt,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: 14,
    padding: 16,
    minWidth: 90,
  },
  addOptionText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.text,
    marginTop: 6,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  addMenu: {
    position: 'absolute',
    right: 20,
    bottom: 90,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 16,
    padding: 8,
    shadowColor: colors.black,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  addMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    borderRadius: 10,
  },
  addMenuIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  addMenuText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: colors.text,
  },
  bottomPadding: {
    height: 100,
  },
  groceryContent: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  groceryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  groceryHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
    marginRight: 12,
  },
  groceryHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexShrink: 0,
  },
  groceryTitle: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: colors.text,
    flexShrink: 1,
  },
  groceryProgress: {
    backgroundColor: colors.success,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  groceryProgressText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.white,
  },
  groceryDeleteBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  groceryCategory: {
    marginBottom: 20,
  },
  groceryCategoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  groceryCategoryEmoji: {
    fontSize: 18,
  },
  groceryCategoryTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.text,
  },
  groceryItemCard: {
    backgroundColor: colors.white,
    borderWidth: 0,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    padding: 14,
  },
  groceryItemCardChecked: {
    backgroundColor: colors.cardAlt,
  },
  groceryItemTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  groceryItemEmoji: {
    fontSize: 28,
  },
  groceryCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.borderLight,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  groceryCheckboxChecked: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  groceryItemContent: {
    flex: 1,
  },
  groceryItemName: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: colors.text,
  },
  groceryItemNameChecked: {
    textDecorationLine: 'line-through',
    color: colors.textSecondary,
  },
  groceryItemAmount: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 2,
  },
  groceryGroupToggle: {
    flexDirection: 'row' as const,
    backgroundColor: colors.cardAlt,
    borderRadius: 10,
    padding: 3,
    marginBottom: 16,
  },
  groceryGroupBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center' as const,
  },
  groceryGroupBtnActive: {
    backgroundColor: colors.text,
  },
  groceryGroupBtnText: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.textSecondary,
  },
  groceryGroupBtnTextActive: {
    color: colors.white,
  },
  groceryRecipeGroup: {
    marginBottom: 12,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: 16,
    overflow: 'hidden' as const,
  },
  groceryRecipeHeader: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    padding: 14,
    backgroundColor: colors.cardAlt,
  },
  groceryRecipeHeaderLeft: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    flex: 1,
    gap: 10,
  },
  groceryRecipeIcon: {
    fontSize: 14,
  },
  groceryRecipeName: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
  },
  groceryRecipeCount: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 2,
  },
  groceryRecipeBadge: {
    backgroundColor: colors.primaryLight,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  groceryRecipeBadgeComplete: {
    backgroundColor: colors.mintLight,
  },
  groceryRecipeBadgeText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: colors.primary,
  },
  groceryRecipeBadgeTextComplete: {
    color: colors.success,
  },
  groceryItemRecipe: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: colors.secondary,
    marginTop: 4,
  },
  groceryEmpty: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    marginTop: 20,
  },
  groceryEmptyTitle: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
  },
  groceryEmptyText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 20,
  },
  groceryEmptyTip: {
    backgroundColor: colors.secondaryLight,
    borderRadius: 14,
    padding: 16,
    width: '100%',
  },
  groceryEmptyTipTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 6,
  },
  groceryEmptyTipText: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.secondary,
    lineHeight: 18,
  },
  groceryTip: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: 16,
    padding: 16,
    marginTop: 12,
  },
  groceryTipTitle: {
    fontSize: 14,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 10,
  },
  groceryTipRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 10,
    marginBottom: 8,
  },
  groceryTipText: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    flex: 1,
  },
  groceryWorkflowBanner: {
    backgroundColor: colors.mintLight,
    borderWidth: 1.5,
    borderColor: colors.mint,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  groceryWorkflowSteps: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  groceryWorkflowStep: {
    alignItems: 'center' as const,
    gap: 4,
    flex: 1,
  },
  groceryWorkflowDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.borderLight,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  groceryWorkflowDotActive: {
    backgroundColor: colors.success,
  },
  groceryWorkflowStepText: {
    fontSize: 10,
    fontWeight: '700' as const,
    color: colors.success,
    textAlign: 'center' as const,
  },
  groceryWorkflowStepTextMuted: {
    fontSize: 10,
    fontWeight: '600' as const,
    color: colors.textSecondary,
    textAlign: 'center' as const,
  },
  groceryWorkflowArrow: {
    paddingHorizontal: 4,
    marginBottom: 14,
  },
  moveToKitchenBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.secondaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  modalSafeArea: {
    flex: 1,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  modalCloseBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: colors.text,
  },
  modeTabs: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginTop: 16,
    backgroundColor: colors.cardAlt,
    borderRadius: 12,
    padding: 4,
  },
  modeTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
  },
  modeTabActive: {
    backgroundColor: colors.text,
  },
  modeTabText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.text,
  },
  modeTabTextActive: {
    color: colors.white,
  },
  modalScroll: {
    flex: 1,
  },
  searchSection: {
    padding: 20,
  },
  searchInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    paddingHorizontal: 14,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500' as const,
    color: colors.text,
    paddingVertical: 14,
  },
  searchSectionTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.textSecondary,
    marginTop: 20,
    marginBottom: 12,
  },
  searchResults: {
    gap: 8,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: 14,
    padding: 14,
    gap: 12,
  },
  searchResultEmoji: {
    fontSize: 24,
  },
  searchResultName: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600' as const,
    color: colors.text,
  },
  noResults: {
    alignItems: 'center',
    paddingVertical: 24,
  },
  noResultsText: {
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginBottom: 16,
  },
  addCustomBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.secondary,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 8,
  },
  addCustomBtnText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: colors.white,
  },
  voiceSection: {
    padding: 20,
  },
  voiceQuickBody: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
  },
  voiceQuickTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: colors.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  voiceQuickSubtitle: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  voiceInputWrap: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    padding: 14,
    gap: 12,
    minHeight: 100,
  },
  voiceInput: {
    flex: 1,
    fontSize: 16,
    fontWeight: '500' as const,
    color: colors.text,
    textAlignVertical: 'top',
  },
  voiceHint: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 12,
    textAlign: 'center',
  },
  voiceAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.secondary,
    borderRadius: 14,
    paddingVertical: 16,
    marginTop: 20,
    gap: 8,
  },
  voiceAddBtnDisabled: {
    backgroundColor: colors.borderLight,
  },
  voiceAddBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
  manualSection: {
    padding: 20,
  },
  inputGroup: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 16,
    fontWeight: '500' as const,
    color: colors.text,
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  categoryOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 6,
  },
  categoryOptionSelected: {
    backgroundColor: colors.primaryLight,
    borderColor: colors.primary,
  },
  categoryOptionEmoji: {
    fontSize: 18,
  },
  categoryOptionLabel: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.text,
  },
  categoryOptionLabelSelected: {
    color: colors.primary,
  },
  manualAddBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 16,
    marginTop: 10,
    gap: 8,
  },
  manualAddBtnDisabled: {
    backgroundColor: colors.borderLight,
  },
  manualAddBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
  voiceRecorderContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  voiceRecorderSafe: {
    flex: 1,
  },
  voiceRecorderHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  voiceRecorderBody: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 32,
  },
  voiceRecorderTitle: {
    fontSize: 24,
    fontWeight: '800' as const,
    color: colors.text,
    textAlign: 'center' as const,
    marginBottom: 8,
  },
  voiceRecorderSubtitle: {
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center' as const,
    lineHeight: 22,
    marginBottom: 32,
    paddingHorizontal: 16,
  },
  recordingTimer: {
    fontSize: 48,
    fontWeight: '700' as const,
    color: colors.primary,
    marginBottom: 32,
  },
  micButtonOuter: {
    marginBottom: 24,
  },
  micButton: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: colors.secondary,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    shadowColor: colors.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  micButtonRecording: {
    backgroundColor: colors.error,
    shadowColor: colors.error,
  },
  micHint: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  voiceProcessingWrap: {
    alignItems: 'center' as const,
    gap: 16,
  },
  voiceProcessingText: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: colors.text,
  },
  voiceProcessingSubtext: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  confirmContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  confirmSafe: {
    flex: 1,
  },
  confirmHeader: {
    flexDirection: 'row' as const,
    justifyContent: 'space-between' as const,
    alignItems: 'center' as const,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  scanProcessing: {
    flex: 1,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    gap: 16,
  },
  scanProcessingText: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: colors.text,
  },
  scanProcessingSubtext: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  confirmInfo: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    backgroundColor: colors.mintLight,
    marginHorizontal: 20,
    marginTop: 16,
    borderRadius: 14,
  },
  confirmInfoText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.secondary,
    textAlign: 'center' as const,
    lineHeight: 20,
  },
  confirmList: {
    flex: 1,
    paddingHorizontal: 20,
    marginTop: 12,
  },
  confirmItem: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
    gap: 12,
  },
  confirmItemDeselected: {
    opacity: 0.5,
    backgroundColor: colors.cardAlt,
  },
  confirmCheckbox: {
    width: 26,
    height: 26,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.borderLight,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  confirmCheckboxSelected: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  confirmItemEmoji: {
    fontSize: 28,
  },
  confirmItemInfo: {
    flex: 1,
  },
  confirmItemName: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: colors.text,
  },
  confirmItemNameDeselected: {
    color: colors.textSecondary,
    textDecorationLine: 'line-through' as const,
  },
  confirmItemCategory: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 2,
  },
  confirmActions: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
    gap: 12,
  },
  confirmSelectAll: {
    alignItems: 'center' as const,
    paddingVertical: 8,
  },
  confirmSelectAllText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.secondary,
  },
  confirmAddBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: colors.success,
    borderRadius: 14,
    paddingVertical: 16,
    gap: 8,
  },
  confirmAddBtnDisabled: {
    backgroundColor: colors.borderLight,
  },
  confirmAddBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
});
