import { StyleSheet } from 'react-native';
import colors from '@/constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  safeArea: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: '800' as const,
    color: colors.text,
    letterSpacing: -0.5,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 8,
  },
  headerBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topPanel: {
    paddingBottom: 14,
  },
  filterScroll: {
    maxHeight: 48,
    marginBottom: 10,
  },
  chipHintRow: {
    paddingHorizontal: 20,
  },
  hintPill: {
    alignSelf: 'flex-start',
    backgroundColor: colors.cardAlt,
    borderWidth: 2,
    borderColor: colors.borderLight,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  hintText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: colors.textSecondary,
  },
  filterContainer: {
    paddingHorizontal: 20,
    gap: 8,
  },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.borderLight,
  },
  filterChipActive: {
    backgroundColor: colors.text,
    borderColor: colors.text,
  },
  filterText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  filterTextActive: {
    color: colors.white,
  },
  scroll: {
    flex: 1,
    paddingHorizontal: 16,
  },
  recipesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  recipeCard: {
    width: '47%',
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 18,
    overflow: 'hidden',
  },
  recipeCardRotateLeft: {
    transform: [{ rotate: '-1deg' }],
  },
  recipeCardRotateRight: {
    transform: [{ rotate: '1deg' }],
  },
  recipeImageWrap: {
    position: 'relative',
  },
  recipeImage: {
    width: '100%',
    height: 130,
    backgroundColor: colors.cardAlt,
  },
  recipeImagePlaceholder: {
    width: '100%',
    height: 130,
    backgroundColor: colors.cardAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  placeholderEmoji: {
    fontSize: 40,
  },
  savingsBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: colors.success,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  savingsText: {
    fontSize: 11,
    fontWeight: '700' as const,
    color: colors.white,
  },
  recipeInfo: {
    padding: 12,
  },
  recipeTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    lineHeight: 20,
    marginBottom: 8,
  },
  recipeMeta: {
    flexDirection: 'row',
    gap: 12,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  emptyScroll: {
    flex: 1,
  },
  emptyScrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  quickStartSection: {
    marginBottom: 20,
  },
  quickStartTitle: {
    fontSize: 13,
    fontWeight: '800' as const,
    color: colors.textSecondary,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  quickStartGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  quickStartCard: {
    flex: 1,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 16,
    padding: 14,
    alignItems: 'center',
    position: 'relative',
  },
  quickStartIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  quickStartLabel: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.text,
    textAlign: 'center',
    lineHeight: 17,
  },
  quickStartBadge: {
    position: 'absolute',
    top: 8,
    right: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: colors.text,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  quickStartBadgeText: {
    fontSize: 9,
    fontWeight: '800' as const,
    color: colors.white,
  },
  emptyCard: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  emptyPattern: {
    position: 'absolute',
    top: 0,
    right: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 60,
    gap: 8,
    padding: 12,
  },
  patternDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.comic.yellow,
  },
  emptyTotie: {
    width: 100,
    height: 100,
    marginBottom: 16,
  },
  emptyTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
  },
  emptySubtext: {
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  emptyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 24,
  },
  emptyButtonText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
  filterEmptyCard: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 24,
    padding: 32,
    alignItems: 'center',
    marginBottom: 16,
  },
  filterEmptyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  filterEmptyTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  filterEmptySubtext: {
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  filterEmptyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 24,
  },
  filterEmptyButtonText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
  filterEmptyTip: {
    backgroundColor: colors.cardAlt,
    borderRadius: 16,
    padding: 16,
    borderWidth: 2,
    borderColor: colors.borderLight,
  },
  filterEmptyTipLabel: {
    fontSize: 13,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 4,
  },
  filterEmptyTipText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  filterEmptySavings: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: colors.borderLight,
  },
  filterEmptySavingsTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 16,
    textAlign: 'center',
  },
  filterEmptySavingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
  },
  filterEmptySavingsItem: {
    alignItems: 'center',
  },
  filterEmptySavingsValue: {
    fontSize: 28,
    fontWeight: '800' as const,
    color: colors.text,
  },
  filterEmptySavingsLabel: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 2,
  },
  filterEmptySavingsArrow: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.cardAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterEmptySavingsArrowText: {
    fontSize: 18,
    color: colors.textSecondary,
  },
  filterEmptyQuickIdeas: {
    backgroundColor: '#FFF8E1',
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: '#FFE082',
  },
  filterEmptyQuickTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 12,
  },
  filterEmptyQuickList: {
    gap: 8,
  },
  filterEmptyQuickItem: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  filterEmptyFavTip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FCE4EC',
    borderRadius: 16,
    padding: 16,
    gap: 12,
    borderWidth: 2,
    borderColor: '#F8BBD9',
  },
  filterEmptyFavTipIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterEmptyFavTipText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500' as const,
    color: '#880E4F',
    lineHeight: 20,
  },
  fab: {
    position: 'absolute',
    right: 20,
    bottom: 20,
    width: 60,
    height: 60,
    borderRadius: 20,
    backgroundColor: colors.secondary,
    borderWidth: 2,
    borderColor: colors.black,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: colors.black,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
  },
  addMenuBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 98,
  },
  addMenu: {
    position: 'absolute',
    right: 20,
    bottom: 90,
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 18,
    padding: 8,
    width: 220,
    shadowColor: colors.black,
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 8,
    zIndex: 99,
  },
  addMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 12,
  },
  addMenuIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  addMenuContent: {
    flex: 1,
  },
  addMenuTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
  },
  addMenuSubtext: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  bottomPadding: {
    height: 100,
  },
  cookbooksScrollContent: {
    paddingBottom: 100,
  },
  bookshelfHeader: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  bookshelfTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  bookshelfTitle: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: colors.text,
  },
  bookshelfSubtitle: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  addCookbookBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    marginHorizontal: 20,
    marginBottom: 20,
    padding: 16,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.black,
    borderStyle: 'dashed',
  },
  addCookbookIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.secondaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  addCookbookText: {
    flex: 1,
  },
  addCookbookTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.text,
  },
  addCookbookSubtext: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  bookshelfGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 16,
    gap: 12,
  },
  cookbookCard: {
    width: '47%',
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 16,
    overflow: 'hidden',
    flexDirection: 'row',
  },
  cookbookCardLeft: {
    transform: [{ rotate: '-1deg' }],
  },
  cookbookSpine: {
    width: 8,
  },
  cookbookCover: {
    flex: 1,
  },
  cookbookImage: {
    width: '100%',
    height: 100,
  },
  cookbookPlaceholder: {
    width: '100%',
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cookbookInfo: {
    padding: 10,
  },
  cookbookTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
    lineHeight: 18,
    marginBottom: 2,
  },
  cookbookAuthor: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginBottom: 6,
  },
  cookbookMeta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  cookbookRecipeCount: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: colors.secondary,
  },
  selectedIndicator: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.secondary,
    borderWidth: 2,
    borderColor: colors.white,
  },
  cookbookRecipesSection: {
    marginTop: 24,
    paddingHorizontal: 20,
  },
  cookbookRecipesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  cookbookRecipesTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.text,
  },
  noCookbookRecipes: {
    backgroundColor: colors.cardAlt,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
  },
  noCookbookRecipesText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: colors.text,
    marginBottom: 4,
  },
  noCookbookRecipesSubtext: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  cookbookGenerating: {
    backgroundColor: colors.cardAlt,
    borderRadius: 16,
    padding: 28,
    alignItems: 'center' as const,
    gap: 12,
  },
  cookbookGeneratingTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    textAlign: 'center' as const,
    marginTop: 4,
  },
  cookbookGeneratingProgress: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.secondary,
    textAlign: 'center' as const,
  },
  cookbookGenCountBadge: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    backgroundColor: 'rgba(0,105,92,0.08)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginTop: 4,
  },
  cookbookGenCountText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.secondary,
  },
  generateCookbookBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    backgroundColor: colors.secondary,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    gap: 8,
    marginTop: 12,
  },
  generateCookbookBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.white,
  },
  emptyCookbookState: {
    backgroundColor: colors.white,
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: colors.black,
    padding: 32,
    alignItems: 'center',
  },
  emptyCookbookTitle: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyCookbookText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  pageBadge: {
    position: 'absolute',
    bottom: 8,
    left: 8,
    backgroundColor: 'rgba(0,0,0,0.7)',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  pageText: {
    fontSize: 10,
    fontWeight: '700' as const,
    color: colors.white,
  },
  cookbookSource: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 6,
  },
  cookbookSourceText: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    flex: 1,
  },
  quickStartGridSecond: {
    marginTop: 10,
  },
  quickStartCardWide: {
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: colors.white,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: colors.black,
    width: '100%',
    maxWidth: 400,
    padding: 24,
  },
  modalContentLarge: {
    backgroundColor: colors.white,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: colors.black,
    width: '100%',
    maxWidth: 400,
    maxHeight: '85%',
    padding: 24,
  },
  tabSelector: {
    flexDirection: 'row',
    backgroundColor: colors.cardAlt,
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  tabActive: {
    backgroundColor: colors.text,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.text,
  },
  tabTextActive: {
    color: colors.white,
  },
  tabContent: {
    minHeight: 280,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.cardAlt,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.borderLight,
    paddingHorizontal: 14,
    gap: 10,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 16,
    fontWeight: '500' as const,
    color: colors.text,
  },
  searchResults: {
    flex: 1,
    maxHeight: 220,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: colors.cardAlt,
    borderRadius: 12,
    marginBottom: 8,
  },
  searchResultCover: {
    width: 50,
    height: 70,
    borderRadius: 6,
    backgroundColor: colors.borderLight,
  },
  searchResultCoverPlaceholder: {
    width: 50,
    height: 70,
    borderRadius: 6,
    backgroundColor: colors.borderLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchResultInfo: {
    flex: 1,
    marginLeft: 12,
  },
  searchResultTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 2,
  },
  searchResultAuthor: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  searchResultYear: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 2,
  },
  noResults: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  noResultsText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: colors.text,
    marginBottom: 4,
  },
  noResultsSubtext: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  searchHint: {
    alignItems: 'center',
    paddingVertical: 50,
    gap: 8,
  },
  searchHintText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  searchHintSubtext: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.borderLight,
  },
  scannerPlaceholder: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    gap: 8,
  },
  scannerPlaceholderTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: colors.text,
    marginTop: 8,
  },
  scannerPlaceholderText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  isbnInputContainer: {
    width: '100%',
    marginTop: 24,
  },
  isbnInputLabel: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.text,
    marginBottom: 8,
  },
  isbnInputRow: {
    flexDirection: 'row',
    gap: 8,
  },
  isbnInput: {
    flex: 1,
    backgroundColor: colors.cardAlt,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.borderLight,
    padding: 14,
    fontSize: 16,
    fontWeight: '500' as const,
    color: colors.text,
  },
  isbnLookupBtn: {
    width: 50,
    height: 50,
    borderRadius: 12,
    backgroundColor: colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.black,
  },
  isbnLookupBtnDisabled: {
    opacity: 0.6,
  },
  permissionBtn: {
    marginTop: 16,
    backgroundColor: colors.secondary,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.black,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  permissionBtnText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.white,
  },
  scannerContainer: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
    position: 'relative',
  },
  scanner: {
    flex: 1,
  },
  scannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scannerFrame: {
    width: 220,
    height: 120,
    position: 'relative',
  },
  scannerCorner: {
    position: 'absolute',
    width: 24,
    height: 24,
    borderColor: colors.white,
  },
  scannerCornerTL: {
    top: 0,
    left: 0,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderTopLeftRadius: 8,
  },
  scannerCornerTR: {
    top: 0,
    right: 0,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderTopRightRadius: 8,
  },
  scannerCornerBL: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderBottomLeftRadius: 8,
  },
  scannerCornerBR: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderBottomRightRadius: 8,
  },
  scannerLoading: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  scannerLoadingText: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: colors.white,
  },
  scannerHint: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 10,
    padding: 12,
  },
  scannerHintText: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.white,
    textAlign: 'center',
  },
  selectedBookPreview: {
    alignItems: 'center',
    marginBottom: 16,
    position: 'relative',
  },
  selectedBookCover: {
    width: 80,
    height: 110,
    borderRadius: 8,
    backgroundColor: colors.borderLight,
  },
  clearSelectedBook: {
    position: 'absolute',
    top: -6,
    right: '35%',
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.text,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: colors.text,
  },
  modalBody: {
    marginBottom: 24,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: colors.cardAlt,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.borderLight,
    padding: 14,
    fontSize: 16,
    fontWeight: '500' as const,
    color: colors.text,
  },
  modalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.secondary,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.black,
    paddingVertical: 16,
  },
  modalButtonDisabled: {
    opacity: 0.5,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
  foodDumpHeader: {
    marginBottom: 16,
  },
  foodDumpTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 6,
  },
  foodDumpTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: colors.text,
  },
  foodDumpSubtitle: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  addIdeaBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    marginBottom: 20,
    padding: 16,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.black,
    borderStyle: 'dashed',
  },
  addIdeaIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#FEF3C7',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  addIdeaText: {
    flex: 1,
  },
  addIdeaTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.text,
  },
  addIdeaSubtext: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  ideasList: {
    marginBottom: 20,
  },
  ideasListTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.textSecondary,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  ideaCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    padding: 14,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.borderLight,
    marginBottom: 10,
  },
  ideaTypeIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  ideaContent: {
    flex: 1,
  },
  ideaText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: colors.text,
    lineHeight: 20,
  },
  ideaSourceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  ideaSource: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  ideaActions: {
    flexDirection: 'row',
    gap: 8,
  },
  ideaActionBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.secondaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ideaDeleteBtn: {
    backgroundColor: '#FEE2E2',
  },
  foodDumpEmptyCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: colors.black,
    padding: 32,
    alignItems: 'center',
    marginBottom: 20,
  },
  foodDumpEmptyTitle: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  foodDumpEmptyText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  foodDumpTips: {
    backgroundColor: '#FEF3C7',
    borderRadius: 16,
    padding: 20,
    borderWidth: 2,
    borderColor: '#FCD34D',
  },
  foodDumpTipsTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 12,
  },
  foodDumpTipsList: {
    gap: 8,
  },
  foodDumpTipItem: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: '#92400E',
  },
  ideaTypeSelector: {
    flexDirection: 'row',
    backgroundColor: colors.cardAlt,
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  ideaTypeTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  ideaTypeTabActive: {
    backgroundColor: colors.text,
  },
  ideaTypeTabText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.text,
  },
  ideaTypeTabTextActive: {
    color: colors.white,
  },
  ideaInput: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  processingOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  processingCard: {
    backgroundColor: colors.white,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: colors.black,
    padding: 32,
    width: '100%',
    maxWidth: 340,
    alignItems: 'center',
  },
  processingIconWrap: {
    width: 80,
    height: 80,
    borderRadius: 24,
    backgroundColor: colors.secondaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  processingSuccessIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#DCFCE7',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  processingErrorIcon: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#FEE2E2',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  processingTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 8,
    textAlign: 'center',
  },
  processingSubtext: {
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  processingSteps: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  processingStepItem: {
    alignItems: 'center',
    gap: 6,
  },
  processingStepActive: {},
  processingStepDone: {},
  processingStepDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.borderLight,
  },
  processingStepDotActive: {
    backgroundColor: colors.secondary,
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  processingStepDotDone: {
    backgroundColor: colors.success,
  },
  processingStepLine: {
    width: 24,
    height: 2,
    backgroundColor: colors.borderLight,
    marginBottom: 18,
  },
  processingStepText: {
    fontSize: 11,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  processingStepTextActive: {
    color: colors.secondary,
    fontWeight: '700' as const,
  },
  processingDoneBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.secondary,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.black,
    paddingVertical: 14,
    paddingHorizontal: 40,
    marginTop: 8,
  },
  processingDoneBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
  processingDoneBtns: {
    gap: 10,
    alignItems: 'center',
    width: '100%',
    marginTop: 8,
  },
  processingGroceryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.secondary,
    backgroundColor: 'transparent',
  },
  processingGroceryBtnText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  recipePreview: {
    backgroundColor: colors.cardAlt,
    borderRadius: 16,
    padding: 16,
    width: '100%',
    marginBottom: 20,
  },
  recipePreviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  recipePreviewTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.text,
    flex: 1,
  },
  recipePreviewStats: {
    flexDirection: 'row',
    gap: 16,
  },
  recipePreviewStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  recipePreviewStatText: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  processedSection: {
    marginBottom: 20,
  },
  processedSectionTitle: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.success,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  processedCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FDF4',
    padding: 12,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#BBF7D0',
    marginBottom: 8,
  },
  processedCardIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#DCFCE7',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  processedCardContent: {
    flex: 1,
  },
  processedCardText: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textDecorationLine: 'line-through',
  },
  processedCardRecipe: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.success,
    marginTop: 2,
  },
  nutriBadgesRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 6,
  },
  nutriBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#FFF3E0',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  nutriBadgeSalt: {
    backgroundColor: '#E8F5E9',
  },
  nutriBadgeText: {
    fontSize: 10,
    fontWeight: '700' as const,
    color: '#E65100',
  },
  nutriBadgeTextSmall: {
    fontSize: 10,
    fontWeight: '600' as const,
    color: '#2E7D32',
  },
  detailModalContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  detailSafeArea: {
    flex: 1,
  },
  detailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 2,
    borderBottomColor: colors.borderLight,
    backgroundColor: colors.white,
  },
  detailCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.cardAlt,
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailDeleteBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#FFF0F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  detailHeaderTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700' as const,
    color: colors.text,
    textAlign: 'center',
    marginHorizontal: 12,
  },
  detailScroll: {
    flex: 1,
  },
  detailImage: {
    width: '100%',
    height: 220,
    backgroundColor: colors.cardAlt,
  },
  detailBody: {
    padding: 20,
  },
  detailTitle: {
    fontSize: 26,
    fontWeight: '800' as const,
    color: colors.text,
    letterSpacing: -0.5,
    marginBottom: 12,
  },
  nutritionRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  nutritionBadge: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: '#FFF3E0',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: '#FFE0B2',
  },
  nutritionBadgeGreen: {
    backgroundColor: '#E8F5E9',
    borderColor: '#C8E6C9',
  },
  nutritionBadgeYellow: {
    backgroundColor: '#FFF8E1',
    borderColor: '#FFE082',
  },
  nutritionBadgeRed: {
    backgroundColor: '#FFEBEE',
    borderColor: '#FFCDD2',
  },
  nutritionBadgeIcon: {
    fontSize: 14,
  },
  nutritionBadgeValue: {
    fontSize: 14,
    fontWeight: '800' as const,
    color: '#E65100',
  },
  nutritionBadgeLabel: {
    fontSize: 11,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  nutritionTextGreen: {
    color: '#059669',
  },
  nutritionTextYellow: {
    color: '#D97706',
  },
  nutritionTextRed: {
    color: '#DC2626',
  },
  detailMetaRow: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 24,
  },
  detailMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  detailMetaText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  detailSectionTitle: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: colors.text,
    marginBottom: 14,
    marginTop: 8,
  },
  ingredientList: {
    gap: 10,
    marginBottom: 24,
  },
  ingredientListItem: {
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.borderLight,
    borderRadius: 14,
    padding: 14,
  },
  ingredientListTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  ingredientListEmoji: {
    fontSize: 28,
  },
  ingredientListInfo: {
    flex: 1,
  },
  ingredientListName: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    textTransform: 'capitalize' as const,
  },
  ingredientListAmount: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 2,
  },
  detailInstructionRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  detailInstructionNum: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    marginTop: 2,
  },
  detailInstructionNumText: {
    fontSize: 14,
    fontWeight: '800' as const,
    color: colors.white,
  },
  detailInstructionText: {
    flex: 1,
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.text,
    lineHeight: 22,
  },
  detailActions: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    gap: 10,
    padding: 16,
    paddingBottom: 32,
    backgroundColor: colors.white,
    borderTopWidth: 2,
    borderTopColor: colors.borderLight,
  },
  detailGroceryBtn: {
    flex: 0.8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.secondaryLight,
    borderWidth: 2,
    borderColor: colors.secondary,
    borderRadius: 14,
    paddingVertical: 14,
  },
  detailGroceryBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  detailStartCookingBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.primary,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    paddingVertical: 14,
  },
  detailStartCookingBtnText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.white,
  },
  cookingContainer: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  cookingSafeArea: {
    flex: 1,
  },
  cookingHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  cookingBackBtn: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cookingTitleWrap: {
    flex: 1,
    alignItems: 'center',
    marginHorizontal: 12,
  },
  cookingTitle: {
    fontSize: 18,
    fontWeight: '700' as const,
    color: colors.white,
  },
  cookingProgress: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: 'rgba(255,255,255,0.7)',
    marginTop: 2,
  },
  cookingProgressBar: {
    height: 4,
    backgroundColor: 'rgba(255,255,255,0.2)',
    marginHorizontal: 16,
    borderRadius: 2,
    overflow: 'hidden' as const,
  },
  cookingProgressFill: {
    height: '100%' as const,
    backgroundColor: colors.white,
    borderRadius: 2,
  },
  cookingContent: {
    flex: 1,
    marginTop: 24,
  },
  cookingContentInner: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  stepCard: {
    backgroundColor: colors.white,
    borderRadius: 24,
    padding: 24,
    minHeight: 200,
  },
  stepNumberBadge: {
    alignSelf: 'flex-start' as const,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  stepNumberText: {
    fontSize: 18,
    fontWeight: '800' as const,
    color: colors.white,
  },
  stepInstruction: {
    fontSize: 20,
    fontWeight: '600' as const,
    color: colors.text,
    lineHeight: 30,
  },
  cookingNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    gap: 12,
  },
  cookingNavBtn: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  cookingNavBtnDisabled: {
    opacity: 0.4,
  },
  cookingNavBtnText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.white,
  },
  cookingNavBtnTextDisabled: {
    opacity: 0.5,
  },
  nextBtn: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.white,
    borderRadius: 14,
    paddingVertical: 14,
  },
  nextBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.primary,
  },
  finishBtn: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.success,
    borderRadius: 14,
    paddingVertical: 14,
  },
  finishBtnText: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.white,
  },
  headerBtnActive: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  searchBarContainer: {
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  searchBarInner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderWidth: 2,
    borderColor: colors.black,
    borderRadius: 14,
    paddingHorizontal: 14,
    gap: 10,
  },
  searchBarInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 16,
    fontWeight: '500' as const,
    color: colors.text,
  },
  filterSectionLabel: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 10,
    marginTop: 8,
  },
  filterChipsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  filterOptionChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: colors.cardAlt,
    borderWidth: 2,
    borderColor: colors.borderLight,
  },
  filterOptionChipActive: {
    backgroundColor: colors.text,
    borderColor: colors.text,
  },
  filterOptionText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  filterOptionTextActive: {
    color: colors.white,
  },
  filterActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  filterClearBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.borderLight,
    alignItems: 'center',
  },
  filterClearBtnText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.textSecondary,
  },
  filterApplyBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: colors.secondary,
    borderWidth: 2,
    borderColor: colors.black,
    alignItems: 'center',
  },
  filterApplyBtnText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.white,
  },
  addManuallyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    marginHorizontal: 20,
    marginBottom: 16,
    padding: 16,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.black,
    gap: 12,
  },
  addManuallyIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#E8F5E9',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addManuallyText: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: colors.text,
  },
  myRecipesEmptyCard: {
    backgroundColor: colors.white,
    marginHorizontal: 20,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: colors.black,
    padding: 24,
    alignItems: 'center',
    position: 'relative' as const,
    overflow: 'hidden' as const,
  },
  myRecipesEmptyDots: {
    position: 'absolute' as const,
    top: 16,
    right: 16,
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 30,
    gap: 4,
  },
  emptyDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  myRecipesEmptyImage: {
    width: 100,
    height: 100,
    marginBottom: 16,
  },
  myRecipesEmptyTitle: {
    fontSize: 20,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 8,
  },
  myRecipesEmptySubtext: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center' as const,
    lineHeight: 20,
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  myRecipesEmptyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 14,
    gap: 8,
  },
  myRecipesEmptyButtonText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.white,
  },
  allEmptyScrollContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  cleanEmptyContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  heroCard: {
    alignItems: 'center' as const,
    backgroundColor: '#FFF8F4',
    borderRadius: 24,
    paddingTop: 28,
    paddingBottom: 20,
    paddingHorizontal: 20,
    marginBottom: 20,
    overflow: 'hidden' as const,
    position: 'relative' as const,
  },
  heroGlow: {
    position: 'absolute' as const,
    top: '15%' as const,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255,107,53,0.08)',
  },
  heroMascotWrap: {
    width: 100,
    height: 100,
    marginBottom: 14,
  },
  heroMascot: {
    width: '100%' as const,
    height: '100%' as const,
  },
  heroTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: colors.text,
    letterSpacing: -0.3,
    marginBottom: 4,
    textAlign: 'center' as const,
  },
  heroSubtitle: {
    fontSize: 14,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'center' as const,
    lineHeight: 20,
  },
  cleanEmptyHero: {
    alignItems: 'flex-start' as const,
    marginBottom: 28,
  },
  cleanEmptyTitle: {
    fontSize: 26,
    fontWeight: '800' as const,
    color: colors.text,
    letterSpacing: -0.5,
    marginBottom: 6,
  },
  cleanEmptySubtitle: {
    fontSize: 15,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    textAlign: 'left' as const,
    lineHeight: 22,
  },
  cleanEmptyActions: {
    backgroundColor: colors.white,
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
  },
  cleanEmptyActionRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingVertical: 16,
    paddingHorizontal: 16,
  },
  cleanEmptyActionIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
    marginRight: 14,
  },
  cleanEmptyActionText: {
    flex: 1,
  },
  cleanEmptyActionTitle: {
    fontSize: 16,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 2,
  },
  cleanEmptyActionSub: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
  },
  cleanEmptyDivider: {
    height: 1,
    backgroundColor: colors.borderLight,
    marginHorizontal: 16,
  },
  featuredCard: {
    marginBottom: 16,
    borderRadius: 20,
    overflow: 'hidden' as const,
    borderWidth: 2,
    borderColor: colors.black,
    backgroundColor: colors.text,
  },
  featuredImage: {
    width: '100%',
    height: 200,
  },
  featuredOverlay: {
    position: 'absolute' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
    padding: 16,
    justifyContent: 'space-between',
  },
  featuredBadge: {
    alignSelf: 'flex-start' as const,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  featuredBadgeText: {
    fontSize: 12,
    fontWeight: '700' as const,
    color: colors.text,
  },
  featuredContent: {
    marginTop: 'auto' as const,
  },
  featuredTitle: {
    fontSize: 22,
    fontWeight: '800' as const,
    color: colors.white,
    marginBottom: 8,
    textShadowColor: 'rgba(0,0,0,0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  featuredMeta: {
    flexDirection: 'row',
    gap: 16,
  },
  featuredMetaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  featuredMetaText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.white,
  },
  recipeCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  recipeCountText: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
  },
  recipeCountDots: {
    flexDirection: 'row',
    gap: 4,
  },
  recipeCountDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  recipeCalorieBadge: {
    position: 'absolute' as const,
    top: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  recipeCalorieText: {
    fontSize: 11,
    fontWeight: '700' as const,
    color: '#E65100',
  },
  metaDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.borderLight,
  },
  keyboardAvoid: {
    flex: 1,
  },
  snappedImagePreview: {
    alignItems: 'center',
    marginBottom: 16,
    position: 'relative',
    borderRadius: 16,
    overflow: 'hidden',
  },
  snappedImage: {
    width: '100%',
    height: 160,
    borderRadius: 16,
    backgroundColor: colors.cardAlt,
  },
  removeSnappedImage: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  browseMoreBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 6,
    paddingVertical: 14,
    paddingHorizontal: 20,
    marginTop: 8,
    borderWidth: 2,
    borderColor: colors.secondary,
    borderRadius: 14,
    borderStyle: 'dashed' as const,
  },
  browseMoreBtnText: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: colors.secondary,
  },
  recipeSelectionOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end' as const,
  },
  recipeSelectionCard: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '85%',
    paddingTop: 20,
    paddingBottom: 32,
  },
  recipeSelectionHeader: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  recipeSelectionTitle: {
    fontSize: 20,
    fontWeight: '800' as const,
    color: colors.text,
    letterSpacing: -0.3,
  },
  recipeSelectionSubtitle: {
    fontSize: 13,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    marginTop: 2,
  },
  recipeSelectionClose: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.cardAlt,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  recipeSelectionActions: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  selectAllBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 8,
  },
  selectAllText: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: colors.text,
  },
  selectedCountText: {
    fontSize: 13,
    fontWeight: '600' as const,
    color: colors.textSecondary,
  },
  recipeSelectionList: {
    paddingHorizontal: 20,
    maxHeight: 400,
  },
  previewRecipeRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 14,
    marginTop: 4,
    gap: 12,
  },
  previewRecipeRowSelected: {
    backgroundColor: 'rgba(0,105,92,0.06)',
  },
  previewCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: colors.borderLight,
    justifyContent: 'center' as const,
    alignItems: 'center' as const,
  },
  previewCheckboxChecked: {
    backgroundColor: colors.secondary,
    borderColor: colors.secondary,
  },
  previewRecipeInfo: {
    flex: 1,
  },
  previewRecipeTitle: {
    fontSize: 15,
    fontWeight: '700' as const,
    color: colors.text,
    marginBottom: 2,
  },
  previewRecipeDesc: {
    fontSize: 12,
    fontWeight: '500' as const,
    color: colors.textSecondary,
    lineHeight: 17,
  },
  previewPageBadge: {
    backgroundColor: colors.cardAlt,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  previewPageText: {
    fontSize: 11,
    fontWeight: '700' as const,
    color: colors.textSecondary,
  },
  addSelectedBtn: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    gap: 8,
    backgroundColor: colors.secondary,
    marginHorizontal: 20,
    marginTop: 16,
    paddingVertical: 16,
    borderRadius: 16,
  },
  addSelectedBtnDisabled: {
    opacity: 0.4,
  },
  addSelectedBtnText: {
    fontSize: 16,
    fontWeight: '800' as const,
    color: colors.white,
  },
});
